# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='ph_high',
            field=models.FloatField(verbose_name='Higher pH Bound'),
        ),
        migrations.AlterField(
            model_name='cropminerals',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_requirements', to='crops.Crop'),
        ),
        migrations.AlterField(
            model_name='regionminerals',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_composition', to='crops.Region'),
        ),
    ]
